version: '2'

# https://hub.docker.com/_/zookeeper/

services:

########### zookeeper cluster ########

  zoo1:
    image: zookeeper:3.4.11
    restart: always
    hostname: zoo1
    ports:
      - 2191:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zookeeper/data/zoo1:/data
      - ./zookeeper/datalog/zoo1:/datalog
      - ./zookeeper/zookeeper.properties:/conf/zoo.cfg
    networks:
      - cluster-network

  zoo2:
    image: zookeeper:3.4.11
    restart: always
    hostname: zoo2
    ports:
      - 2192:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=0.0.0.0:2888:3888 server.3=zoo3:2888:3888
    volumes:
      - ./zookeeper/data/zoo2:/data
      - ./zookeeper/datalog/zoo2:/datalog
      - ./zookeeper/zookeeper.properties:/conf/zoo.cfg
    networks:
      - cluster-network

  zoo3:
    image: zookeeper:3.4.11
    restart: always
    hostname: zoo3
    ports:
      - 2193:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=0.0.0.0:2888:3888
    volumes:
      - ./zookeeper/data/zoo3:/data
      - ./zookeeper/datalog/zoo3:/datalog
      - ./zookeeper/zookeeper.properties:/conf/zoo.cfg
    networks:
      - cluster-network

########### zookeeper tools ########

  # http://localhost:8000
  web:
    image: elkozmon/zoonavigator-web:0.4.0
    container_name: zoonavigator-web
    ports:
     - 8000:8000
    environment:
      API_HOST: "api"
      API_PORT: 9000
    links:
     - api
    depends_on:
     - api
    restart: always
    networks:
      - cluster-network

  api:
    image: elkozmon/zoonavigator-api:0.4.0
    container_name: zoonavigator-api
    environment:
      SERVER_HTTP_PORT: 9000
    restart: always
    networks:
      - cluster-network

########### kafka cluster ########

  kafka1:
    image: wurstmeister/kafka:latest
    ports:
       - 9094:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka
      # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
      # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka1:9094
      # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9094
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_HOST_NAME:
      KAFKA_ADVERTISED_PORT: 9094
    depends_on:
     - zoo1
     - zoo2
     - zoo3
    networks:
      cluster-network:
          ipv4_address: 172.16.238.19

  kafka2:
     image: wurstmeister/kafka:latest
     ports:
        - 9095:9092
     environment:
       KAFKA_BROKER_ID: 2
       KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka
       # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
       # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka1:9094
       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9095
       KAFKA_LISTENERS: PLAINTEXT://kafka2:9095
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
     depends_on:
      - zoo1
      - zoo2
      - zoo3
     networks:
      - cluster-network

  kafka3:
     image: wurstmeister/kafka:latest
     ports:
        - 9096:9092
     environment:
       KAFKA_BROKER_ID: 3
       KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka
       # KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9094
       # KAFKA_ADVERTISED_LISTENERS: INSIDE://:9092,OUTSIDE://kafka1:9094
       # KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9096
       KAFKA_LISTENERS: PLAINTEXT://:9096
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
     depends_on:
      - zoo1
      - zoo2
      - zoo3
     networks:
      - cluster-network

########### kafka tools ########

  # https://github.com/yahoo/kafka-manager
  # http://localhost:9001/clusters/docker-kafka/topics
  kafka-manager:
    image: qnib/plain-kafka-manager:latest
    environment:
      ZOOKEEPER_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
      APPLICATION_SECRET: change_me_please
    ports:
      - 9001:9000
    restart: always
    networks:
      - cluster-network

  # https://github.com/confluentinc/schema-registry
  confluent-schema-registry:
    image: confluentinc/cp-schema-registry:4.1.0
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zoo1:2181,zoo2:2181,zoo3:2181/kafka
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8091
      SCHEMA_REGISTRY_HOST_NAME: confluent-schema-registry
    restart: always
    networks:
      - cluster-network

  # https://github.com/confluentinc/kafka-rest
  confluent-rest-proxy:
    image: confluentinc/cp-kafka-rest:4.1.0
    environment:
      KAFKA_REST_BOOTSTRAP_SERVERS: 172.16.238.19:9092,kafka2:9092,kafka3:9092
      KAFKA_REST_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka
      KAFKA_REST_LISTENERS: http://0.0.0.0:8092/
      KAFKA_REST_SCHEMA_REGISTRY_URL: http://confluent-schema-registry:8091/
      KAFKA_REST_HOST_NAME: confluent-rest-proxy
      # please replace this setting by the IP of your web tools server
      #KAFKA_REST_HOST_NAME: "54.206.91.106"
    depends_on:
      - confluent-schema-registry
    restart: always
    networks:
      cluster-network:
          ipv4_address: 172.16.238.41

  # https://github.com/Landoop/kafka-topics-ui
  # http://localhost:8001/#/
  kafka-topics-ui:
    image: landoop/kafka-topics-ui:latest
    ports:
       - 8001:8000
    environment:
      KAFKA_REST_PROXY_URL: http://confluent-rest-proxy:8092
      PROXY: "TRUE"
    depends_on:
      - confluent-rest-proxy
    restart: always
    networks:
      - cluster-network

networks:
  cluster-network:
    #driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/26
